# .overcommit.yml

PreCommit:
  RuboCop:
    enabled: true
    command: ['bundle', 'exec', 'rubocop', '--autocorrect']
    on_warn: fail

CommitMsg:
  MessageFormat:
    enabled: false

  CustomBranchMessageFormat:
    enabled: true
    description: '브랜치에 맞는 커밋 메시지 형식을 강제'
    required_executable: './.git-hooks/check-commit-msg'