PreCommit:
  RuboCop:
    enabled: true
    command: ['bundle', 'exec', 'rubocop', '--autocorrect']
    on_warn: fail

CommitMsg:
  CustomBranchMessageFormat:
    enabled: true
    description: '브랜치에 맞는 커밋 메시지 형식을 지켜야 합니다.'
    exclude_branches:
      - main
      - develop
    required_pattern: '/^\[(DEV\d{4}|fix_ng_\d+|refactor_\d+)\]/'
    problem_on_unmatch: '커밋 메시지는 [DEV0001], [fix_ng_1234], [refactor_1234] 형식을 따라야 합니다.'