PreCommit:
  RuboCop:
    enabled: true
    command: ['bundle', 'exec', 'rubocop', '--autocorrect']
    on_warn: fail

CommitMsg:
  # 기본 MessageFormat은 끄고(원하면 두어도 상관없지만 우선 비활성 추천)
  MessageFormat:
    enabled: false

  # 커스텀 스크립트 연결
  CustomBranchMessageFormat:
    enabled: true
    description: '브랜치에 맞는 커밋 메시지 형식을 강제'
    required_executable: './.git-hooks/check-commit-msg'
